'use strict';

/**
 * ProjectProfileV1 Registry.
 *
 * HONESTY NOTE: the governing document (section 6) lists 22 candidate profiles.
 * 14 are implemented here with real triggers/implications. The other 8 are listed
 * in PROFILE_REGISTRY_DEFERRED with NOT_IMPLEMENTED_YET — declared, not faked.
 *
 * `triggers.keywords` are matched (case-insensitive, Arabic+English) against
 * project_name + project_goal + relevant advanced-input free text. This is a
 * deterministic heuristic, NOT an AI classifier — documented as such everywhere
 * it is surfaced to the user (source: INFERRED_DEFAULT, never CONFIRMED).
 */

const PROFILE_REGISTRY_VERSION = '1.0';

const PROFILE_REGISTRY = [
  {
    id: 'WEB_APPLICATION',
    version: '1.0',
    description: 'تطبيق ويب عام بلا خصائص مميزة إضافية (نقطة البداية الافتراضية).',
    triggers: { keywords: ['موقع', 'تطبيق ويب', 'website', 'web app', 'منصة'] },
    required_capabilities: ['responsive_ui', 'basic_navigation'],
    optional_capabilities: ['auth'],
    security_implications: ['input_validation', 'output_escaping'],
    data_implications: ['basic_persistence'],
    ux_implications: ['loading_states', 'empty_states', 'error_states'],
    architecture_implications: ['layered_or_client_server'],
    testing_implications: ['unit', 'e2e_core_flow'],
    production_implications: ['basic_deployment'],
  },
  {
    id: 'WEB_SAAS',
    version: '1.0',
    description: 'منتج ويب يُقدَّم كخدمة مستمرة لمستخدمين مسجَّلين.',
    triggers: { keywords: ['saas', 'اشتراك', 'خدمة مستمرة', 'subscription', 'منصة خدمية'] },
    required_capabilities: ['auth', 'user_accounts', 'billing_hooks_optional'],
    optional_capabilities: ['multi_tenancy'],
    security_implications: ['session_management', 'rbac_basic'],
    data_implications: ['user_scoped_data'],
    ux_implications: ['onboarding_flow', 'account_settings'],
    architecture_implications: ['clean_or_layered'],
    testing_implications: ['auth_tests', 'billing_tests_if_applicable'],
    production_implications: ['uptime_monitoring'],
  },
  {
    id: 'MULTI_TENANT_SAAS',
    version: '1.0',
    description: 'SaaS يخدم عدة مؤسسات/عملاء منفصلين تتطلب بياناتهم عزلًا صارمًا.',
    triggers: { keywords: ['متعدد المستأجرين', 'multi-tenant', 'multi tenant', 'عدة مؤسسات', 'عدة شركات', 'عدة فروع'] },
    required_capabilities: ['tenant_isolation', 'rbac', 'per_tenant_admin'],
    optional_capabilities: ['white_labeling'],
    security_implications: ['tenant_isolation', 'row_level_security', 'cross_tenant_leak_prevention'],
    data_implications: ['tenant_scoped_schema_or_rls'],
    ux_implications: ['tenant_switcher', 'org_admin_console'],
    architecture_implications: ['clean_hexagonal_preferred'],
    testing_implications: ['tenant_isolation_tests', 'rbac_tests'],
    production_implications: ['per_tenant_backup_strategy'],
  },
  {
    id: 'MOBILE_APPLICATION',
    version: '1.0',
    description: 'تطبيق محمول (iOS/Android) كواجهة أساسية.',
    triggers: { keywords: ['تطبيق جوال', 'تطبيق موبايل', 'mobile app', 'flutter', 'android', 'ios'] },
    required_capabilities: ['offline_tolerant_ui', 'push_notifications_optional'],
    optional_capabilities: ['biometric_auth'],
    security_implications: ['secure_local_storage'],
    data_implications: ['local_cache_sync'],
    ux_implications: ['touch_targets', 'mobile_navigation'],
    architecture_implications: ['feature_first_layered'],
    testing_implications: ['widget_tests', 'device_matrix_note'],
    production_implications: ['app_store_release_process'],
  },
  {
    id: 'PUBLIC_PORTAL',
    version: '1.0',
    description: 'موقع عام مفتوح للجمهور، غالبًا بلا تسجيل دخول إلزامي.',
    triggers: { keywords: ['موقع عام', 'بوابة عامة', 'public website', 'public portal', 'موقع تعريفي'] },
    required_capabilities: ['seo_basics', 'public_content_pages'],
    optional_capabilities: ['contact_form'],
    security_implications: ['basic_input_validation'],
    data_implications: ['mostly_static_or_cms'],
    ux_implications: ['fast_first_paint', 'accessible_public_content'],
    architecture_implications: ['layered_simple'],
    testing_implications: ['e2e_core_flow'],
    production_implications: ['cdn_caching_optional'],
  },
  {
    id: 'INTERNAL_OPERATIONS_SYSTEM',
    version: '1.0',
    description: 'أداة داخلية لفريق أو قسم محدد، غير متاحة للجمهور.',
    triggers: { keywords: ['نظام داخلي', 'internal tool', 'أداة داخلية للموظفين', 'ادارة داخلية'] },
    required_capabilities: ['internal_auth', 'audit_log'],
    optional_capabilities: ['role_based_views'],
    security_implications: ['internal_network_assumption_documented'],
    data_implications: ['operational_data_model'],
    ux_implications: ['efficiency_over_polish'],
    architecture_implications: ['layered_simple'],
    testing_implications: ['unit', 'core_workflow_e2e'],
    production_implications: ['internal_deployment_target'],
  },
  {
    id: 'ADMIN_DASHBOARD',
    version: '1.0',
    description: 'لوحة تحكم إدارية لعرض وإدارة بيانات/مستخدمين/عمليات.',
    triggers: { keywords: ['لوحة تحكم', 'dashboard', 'admin panel', 'لوحة إدارة'] },
    required_capabilities: ['data_tables', 'filters_search', 'role_based_access'],
    optional_capabilities: ['analytics_widgets'],
    security_implications: ['admin_action_audit_log'],
    data_implications: ['aggregation_queries'],
    ux_implications: ['table_empty_loading_error_states'],
    architecture_implications: ['layered_simple'],
    testing_implications: ['unit', 'e2e_crud'],
    production_implications: ['restricted_access_deployment'],
  },
  {
    id: 'API_SERVICE',
    version: '1.0',
    description: 'خدمة API بلا واجهة مستخدم رسومية مستقلة.',
    triggers: { keywords: ['api فقط', 'api only', 'خدمة api', 'backend service', 'rest api', 'microservice'] },
    required_capabilities: ['api_contracts', 'input_validation'],
    optional_capabilities: ['rate_limiting'],
    security_implications: ['auth_token_validation', 'input_validation_strict'],
    data_implications: ['service_owned_data_store'],
    // Deliberately EMPTY — proves section 13's literal example: API-only has no
    // mobile navigation / no responsive UI requirement. Tested explicitly.
    ux_implications: [],
    architecture_implications: ['layered_or_hexagonal'],
    testing_implications: ['contract_tests', 'integration_tests'],
    production_implications: ['api_versioning_strategy'],
  },
  {
    id: 'AI_ASSISTANT',
    version: '1.0',
    description: 'مساعد يعتمد على نموذج ذكاء اصطناعي للإجابة أو المساعدة في مهام.',
    triggers: { keywords: ['مساعد ذكاء اصطناعي', 'ai assistant', 'chatbot', 'شات بوت', 'مساعد ذكي'] },
    required_capabilities: ['prompt_injection_controls', 'provenance_of_answers'],
    optional_capabilities: ['tool_calling'],
    security_implications: ['prompt_injection_controls', 'content_isolation', 'context_minimization'],
    data_implications: ['conversation_logging_policy'],
    ux_implications: ['uncertainty_display', 'abstention_path'],
    architecture_implications: ['model_provider_boundary'],
    testing_implications: ['golden_eval_set', 'regression_evals'],
    production_implications: ['human_approval_for_sensitive_actions'],
  },
  {
    id: 'DOCUMENT_INTELLIGENCE',
    version: '1.0',
    description: 'نظام يحلل أو يستخرج معلومات من مستندات (بحث، أرشفة، استخراج).',
    triggers: { keywords: ['تحليل مستندات', 'document intelligence', 'استخراج بيانات من ملفات', 'أرشفة ذكية', 'ocr'] },
    required_capabilities: ['document_ingestion', 'extraction_confidence_scoring'],
    optional_capabilities: ['ocr_pipeline'],
    security_implications: ['sensitive_document_handling'],
    data_implications: ['source_document_traceability'],
    ux_implications: ['review_before_commit_ui'],
    architecture_implications: ['pipeline_stages'],
    testing_implications: ['extraction_accuracy_tests'],
    production_implications: ['reprocessing_strategy'],
  },
  {
    id: 'GIS_SYSTEM',
    version: '1.0',
    description: 'نظام يعتمد على بيانات جغرافية/مكانية كجزء أساسي من المنتج.',
    triggers: { keywords: ['gis', 'نظام معلومات جغرافية', 'خرائط', 'جغرافي', 'mapping system'] },
    required_capabilities: ['map_rendering', 'spatial_query'],
    optional_capabilities: ['offline_maps'],
    security_implications: ['sensitive_location_data_handling'],
    data_implications: ['spatial_database_or_layer_storage'],
    ux_implications: ['map_interaction_patterns'],
    architecture_implications: ['layered_with_spatial_layer'],
    testing_implications: ['spatial_query_tests'],
    production_implications: ['map_tile_hosting_strategy'],
  },
  {
    id: 'FINANCIAL_SYSTEM',
    version: '1.1',
    description: 'نظام يتعامل مع معاملات مالية أو محاسبية حساسة.',
    triggers: {
      keywords: ['نظام مالي', 'محاسبة', 'financial system', 'فواتير', 'مدفوعات', 'accounting', 'دفتر الأستاذ', 'ledger', 'مصالحة بنكية'],
      negative_keywords: ['عيادة', 'موعد', 'حجز', 'clinic', 'booking', 'appointment'],
      sensitive: true,
    },
    required_capabilities: ['audit_trail_immutable', 'strong_authorization'],
    optional_capabilities: ['multi_currency'],
    security_implications: ['strong_audit', 'strong_authorization', 'encryption_at_rest_recommended'],
    data_implications: ['immutable_ledger_pattern'],
    ux_implications: ['confirmation_before_irreversible_action'],
    architecture_implications: ['clean_hexagonal_preferred'],
    testing_implications: ['financial_calculation_tests', 'security_testing'],
    production_implications: ['regulatory_requirements_flagged_for_decision'],
  },
  {
    id: 'BOOKING_SYSTEM',
    version: '1.0',
    description: 'نظام حجز مواعيد/موارد (عيادة، فعالية، قاعة...).',
    triggers: { keywords: ['حجز مواعيد', 'booking', 'نظام حجز', 'جدولة مواعيد', 'appointment'] },
    required_capabilities: ['slot_availability', 'booking_confirmation', 'reminders_optional'],
    optional_capabilities: ['waitlist'],
    security_implications: ['booking_data_privacy'],
    data_implications: ['availability_calendar_model'],
    ux_implications: ['calendar_picker_ui'],
    architecture_implications: ['layered_simple'],
    testing_implications: ['double_booking_prevention_tests'],
    production_implications: ['timezone_handling'],
  },
  {
    id: 'ECOMMERCE',
    version: '1.0',
    description: 'متجر إلكتروني لبيع منتجات مع سلة وشراء.',
    triggers: { keywords: ['متجر إلكتروني', 'ecommerce', 'e-commerce', 'سلة شراء', 'بيع منتجات', 'shop'] },
    required_capabilities: ['product_catalog', 'cart', 'checkout'],
    optional_capabilities: ['inventory_management'],
    security_implications: ['payment_data_not_stored_directly'],
    data_implications: ['product_order_inventory_model'],
    ux_implications: ['cart_empty_state', 'order_confirmation'],
    architecture_implications: ['layered_or_clean'],
    testing_implications: ['checkout_flow_e2e'],
    production_implications: ['payment_provider_integration_flagged'],
  },
  {
    id: 'DESKTOP_APPLICATION',
    version: '1.0',
    description: 'تطبيق سطح مكتب أصلي يعمل على جهاز المستخدم مباشرة.',
    triggers: { keywords: ['تطبيق سطح المكتب', 'desktop app', 'desktop application', 'electron', 'تطبيق مكتبي'] },
    required_capabilities: ['desktop_ui', 'local_file_access'],
    optional_capabilities: ['auto_update', 'system_tray_integration'],
    security_implications: ['local_file_permission_scope'],
    data_implications: ['local_data_storage'],
    ux_implications: ['native_platform_conventions'],
    architecture_implications: ['layered_simple'],
    testing_implications: ['desktop_uat'],
    production_implications: ['installer_and_update_channel'],
  },
  {
    id: 'LEGAL_SYSTEM',
    version: '1.0',
    description: 'نظام يتعامل مع بيانات قضايا قانونية أو عقود أو سجلات حساسة من ناحية الامتثال.',
    triggers: {
      keywords: ['قضايا قانونية', 'عقود', 'نظام قانوني', 'legal case', 'contract management', 'compliance'],
      sensitive: true,
    },
    required_capabilities: ['strict_access_control', 'audit_log', 'document_versioning'],
    optional_capabilities: ['e_signature'],
    security_implications: ['privileged_access_separation', 'confidentiality_protection'],
    data_implications: ['legal_retention_period', 'chain_of_custody'],
    ux_implications: ['careful_disclosure_ui'],
    architecture_implications: ['clean_hexagonal_preferred'],
    testing_implications: ['legal_access_control_tests'],
    production_implications: ['regulatory_compliance_review'],
  },
  {
    id: 'RESEARCH_SYSTEM',
    version: '1.0',
    description: 'نظام يدعم جمع وتحليل بيانات بحثية أو أكاديمية.',
    triggers: { keywords: ['بحث علمي', 'بيانات بحثية', 'research', 'dataset', 'academic'] },
    required_capabilities: ['dataset_versioning', 'citation_tracking'],
    optional_capabilities: ['collaboration_tools', 'export_formats'],
    security_implications: ['research_data_access_control'],
    data_implications: ['dataset_backup_and_versioning'],
    ux_implications: ['data_exploration_tools'],
    architecture_implications: ['layered_simple'],
    testing_implications: ['data_integrity_tests'],
    production_implications: ['research_dataset_backup'],
  },
  {
    id: 'CONTENT_PLATFORM',
    version: '1.0',
    description: 'منصة لنشر واستهلاك محتوى تحريري أو إعلامي.',
    triggers: { keywords: ['مدونة', 'نشر محتوى', 'blog', 'cms', 'content platform'] },
    required_capabilities: ['content_editor', 'publishing_workflow'],
    optional_capabilities: ['comments', 'content_scheduling'],
    security_implications: ['content_injection_protection'],
    data_implications: ['content_versioning'],
    ux_implications: ['reading_experience'],
    architecture_implications: ['layered_simple'],
    testing_implications: ['publishing_workflow_tests'],
    production_implications: ['cdn_caching'],
  },
];

const PROFILE_REGISTRY_IMPLEMENTED_THIS_BATCH = ['DESKTOP_APPLICATION', 'LEGAL_SYSTEM', 'RESEARCH_SYSTEM', 'CONTENT_PLATFORM'];

// PROFILE_REGISTRY_DECISIONS — replaces the old PROFILE_REGISTRY_DEFERRED flat
// list. Four of the original eight deferred profiles were implemented in this
// batch (see PROFILE_REGISTRY_IMPLEMENTED_THIS_BATCH above); the remaining four
// get an explicit decision + real rationale instead of a bare "not done yet".
const PROFILE_REGISTRY_DECISIONS = [
  {
    id: 'RAG_KNOWLEDGE_SYSTEM',
    decision: 'REMOVED_WITH_REASON',
    reason: 'يتداخل بنسبة كبيرة مع AI_ASSISTANT وDOCUMENT_INTELLIGENCE معًا، وإضافته كملف تعريف مستقل كان سيضاعف قواعد الامتثال دون قيمة تصنيفية حقيقية جديدة؛ احتياجاته (grounding/citations) مُمثَّلة كقواعد ضمن AI_ASSISTANT بدل ملف تعريف منفصل.',
  },
  {
    id: 'AGENTIC_SYSTEM',
    decision: 'DEFERRED_WITH_REASON',
    reason: 'يحتاج قواعد خاصة بتفويض الأدوات (tool authorization) وموافقة بشرية على الإجراءات عالية الخطورة لم تُختبر بعمق كافٍ في هذه الدفعة؛ تأجيله أفضل من شحن ملف تعريف غير مكتمل الأثر الأمني.',
  },
  {
    id: 'MARKETPLACE',
    decision: 'DEFERRED_WITH_REASON',
    reason: 'يتطلب نموذج طرفين (بائع/مشتري) وتسوية مدفوعات متعددة الأطراف، أعقد من توسعة ECOMMERCE الحالية؛ يحتاج تصميم قواعد مستقل لم يتم تخصيص وقت كافٍ له في هذه الدفعة.',
  },
  {
    id: 'HIGH_ASSURANCE_SYSTEM',
    decision: 'DEFERRED_WITH_REASON',
    reason: 'يفترض معايير امتثال صارمة تتجاوز ما يمكن لهذا المحرك العام أن يضمنه بأمانة دون مدخلات تنظيمية محددة من المستخدم؛ تأجيله يمنع الادعاء الكاذب بتغطية امتثال غير مُتحقق منه.',
  },
];

function getProfileById(id) {
  return PROFILE_REGISTRY.find((p) => p.id === id) || null;
}

module.exports = {
  PROFILE_REGISTRY_VERSION,
  PROFILE_REGISTRY,
  PROFILE_REGISTRY_DECISIONS,
  PROFILE_REGISTRY_IMPLEMENTED_THIS_BATCH,
  getProfileById,
};
